### ISSUE TITLE
Any support planned for 'push' ?

### ISSUE THREAD

**Issue by Ryan-ZA** [timboudreau/acteur#2]
One of the best parts of the netty server is 1st order support for things like websockets and comet. Actueur looks great, but it seems very difficult to add in push support into it. Am I missing anything here and it can be done, or is it a planned feature in the future?

**Comment by timboudreau** [comment]
Long since fixed - websocket support, plus processing the request as soon as the headers arrive for HTTP mode, plus SSE in a separate library, plus a websocket testing framework [blather](https://github.com/timboudreau/blaather).
